AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: nodejs20.x
    Architectures: ["x86_64"]
    Environment:
      Variables:
        NODE_OPTIONS: "--enable-source-maps"
    EphemeralStorage:
      Size: 512
  Api:
    OpenApiVersion: "2.0"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowOrigin: "'*'"
      MaxAge: 600

Resources:
  NodeModulesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: next-dependencies
      Description: Node modules for Next.js application
      ContentUri: layer/
      CompatibleRuntimes:
        - nodejs20.x
      RetentionPolicy: Retain

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      BinaryMediaTypes:
        - "image/*"
        - "multipart/form-data"
      Auth:
        DefaultAuthorizer: NONE
  NestjsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: true
    Properties:
      Handler: lambda.handler
      CodeUri: ./dist
      MemorySize: 3008
      Timeout: 30
      Layers:
        - !Ref NodeModulesLayer
      Environment:
        Variables:
          NEXT_PUBLIC_API_URL: https://dexjouhd4sbdmohnqivcg2bl6i0bitzi.lambda-url.us-west-2.on.aws/api
          NEXT_PUBLIC_COURSE_MARKET_ADDRESS: 0x5DA45119233433327cD77D66EfCdA92edE57Ce78
          NEXT_PUBLIC_YIDENG_TOKEN_ADDRESS: 0xb26BA51DAcc2F8e59CB87ECCD2eC73a2C3540d6f
      Policies:
        - VPCAccessPolicy: {}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref Api
            Auth:
              Authorizer: NONE
      AutoPublishAlias: live

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt NestjsFunction.Arn
